### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by rzezeski**
I've reinstated the unit tests for luwak.  The code in test_helper.erl feels a bit hackish but I just wanted to get the tests working again.

BTW, in order to compile I had to:

1) ./rebar get-deps
2) edit deps/riak_kv/rebar.config and use the {tag, "eper-0.6.0"} syntax
3) rm -rf deps/eper
4) ./rebar get-deps
5) ./rebar compile

### CODE REVIEW

**Comment by slfritchie** [comment]
Ryan, I'm having difficulty with the tests in luwak_checksum_tests.erl,
namely timeouts when storing the very small file in one_off_checksum_test().
See https://gist.github.com/6d436485912b60d3f6db for the output and
some of the hackery I'd crudely added to try to see what was going on.

We're in the middle of preparing the Riak 0.14 release.  Would it be possible
for you to reshape your branch to fit with the "riak-0.14" branch of the
basho/riak repo?  It should also get rid of all/most of the five rebar steps that
you mention in the pull description.

-Scott

**Comment by rzezeski** [comment]
What version of Erlang/OTP did you run this against?  I ran against R14B and I noticed version differences between your application listing and mine.

Also, I have no problem rebasing my branch if someone wants to update luwak master w/ a ref to 0.14.

**Comment by dizzyd** [comment]
We'll revisit merging this after the 0.14 release. Thanks progski!

**Comment by rzezeski** [comment]
I rebased my changes against luwak-1.0.  I only had time to test against R14B on OS X.  I can make another pull request if necessary.

**Comment by beerriot** [comment]
I found that I needed a couple of extra bits to get these unit tests running, so I've pulled these commits into another branch, added my changes, and submitted https://github.com/basho/luwak/pull/5  Please add more there, if needed.

**Pull request closed without merging**
